# Generated by Django 4.0.1 on 2022-03-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_battery_desc_battery_power_camera_desc_camera_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_size',
            old_name='desc',
            new_name='size',
        ),
    ]
