# Generated by Django 4.0.1 on 2022-03-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_desc',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
