# Generated by Django 4.0.1 on 2022-03-26 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 3, 26, 19, 17, 44, 346466, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
