# Generated by Django 4.0.1 on 2022-03-26 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='time',
            field=models.TimeField(auto_now_add=True, default='12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
