# Generated by Django 4.0.1 on 2022-03-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['time']},
        ),
    ]
